### PR TITLE
Release v0.2.1

### PR DESCRIPTION
**Pull request by dmikurube**
@muga After #44 and #45, releasing a new version.

### CODE REVIEW

**Comment by dmikurube** [comment]
(Its base branch is now `configure-incremental-out-of-base-classes`. Change the base to `master` before merging.)

**Comment by dmikurube** [comment]
Suspended while #45 is reconstructed.

**Comment by dmikurube** [comment]
@muga Reopening -- #47 is now available. To release v0.2.1.

**Comment by muga** [comment]
@dmikurube I put LGTM on #47. let's release new one-

**Comment by dmikurube** [comment]
Thanks. Rebased, merging, and releasing!

**Pull request merged**
