### PR TITLE
Release v0.5.5

### PR DESCRIPTION
**Pull request by dmikurube**
@sakama @muga Can you have a look?

It's adding CHANGELOG for v0.5.4 forgotten as well...

### CODE REVIEW

**Review by sakama — APPROVED** [review]
LGTM

**Comment by dmikurube** [comment]
Thanks! Merging...

**Comment by kfitzgerald** [comment]
@dmikurube @muga Thanks! Once this is pushed to maven/bintry/torquebox, I'll finalize that PR for [embulk-output-elasticsearch](https://github.com/kfitzgerald/embulk-output-elasticsearch/tree/fix-embulk-nulls)

**Comment by dmikurube** [comment]
@kfitzgerald v0.5.5 has been released with your PR on Bintray. :)

**Pull request merged**
